sonar.projectKey=student-grade-tracker
sonar.projectName=Student Grade Tracker API
sonar.projectVersion=1.0.0

sonar.sources=src
sonar.tests=tests

sonar.javascript.lcov.reportPaths=coverage/lcov.info

sonar.exclusions=**/node_modules/**,**/coverage/**

sonar.host.url=http://sonarqube:9000
sonar.login=admin
sonar.password=admin123